In [1]:
import numpy as np

In [2]:
import keyword

In [3]:
keyword.kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [4]:
from keyword import kwlist

In [5]:
kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

#numpy

In [6]:
import numpy as np

In [7]:
a=np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [8]:
len(a)

7

In [9]:
a.dtype

dtype('int32')

In [10]:
b=np.array([1.2,2.3])
b

array([1.2, 2.3])

In [11]:
a.size

7

In [12]:
a.shape

(7,)

In [13]:
a.ndim

1

In [14]:
c=np.array([[2,3,4,],[4,5,6],[6,7,8],[9,10,11]])
c

array([[ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
c.shape

(4, 3)

In [16]:
d=np.array([[[2],[3],[4]],[[4],[5],[6]],[[6],[7],[8]],[[9],[10],[11]]])
d

array([[[ 2],
        [ 3],
        [ 4]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11]]])

In [17]:
d.shape

(4, 3, 1)

In [18]:
c.sum()

75

In [19]:
c.mean(axis=1)

array([ 3.,  5.,  7., 10.])

In [20]:
c[0:2,-1]

array([4, 6])

In [56]:
x=np.array([[2,3,4],[4,5,6],[6,7,8],[9,10,11]])

In [57]:
x

array([[ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
x.shape

(4, 3)

In [50]:
y=np.array([[[4,41],[8,81],[7,71]],[[3,31],[1,11],[5,51]],[[6,61],[9,91],[13,131]]])

In [51]:
y

array([[[  4,  41],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [53]:
y.shape

(3, 3, 2)

In [58]:
x

array([[ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [62]:
x[1][0] #want to access any #subscripting i.e row and column

4

In [77]:
x[1,:]#slicing

array([4, 5, 6])

In [68]:
x[0:4:1,2] #here 2 is column or we can say 2 is dimemnsional

array([ 4,  6,  8, 11])

In [80]:
x[:,2:] 


array([[ 4],
       [ 6],
       [ 8],
       [11]])

In [69]:
y

array([[[  4,  41],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [75]:
y[0][1]

array([ 8, 81])

In [73]:
y[0][1][0]


8

In [72]:
y[0:4:1,2]

array([[  7,  71],
       [  5,  51],
       [ 13, 131]])

In [81]:
y

array([[[  4,  41],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [89]:
y[1:,1:,:1]

array([[[ 1],
        [ 5]],

       [[ 9],
        [13]]])

In [92]:
y[1:,0:1]


array([[[ 3, 31]],

       [[ 6, 61]]])

In [93]:
x

array([[ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [96]:
x+3 #we can mathematical operation with array but cant with list etc

array([[ 5,  6,  7],
       [ 7,  8,  9],
       [ 9, 10, 11],
       [12, 13, 14]])

In [99]:
x[0]=1 #whole row

In [103]:
x[1][0]=9 # particular 

In [104]:
x

array([[ 1,  1,  1],
       [ 9,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [105]:
del a[0] #we cant delete like this 

ValueError: cannot delete array elements

In [108]:
x[0,:]=[2,3,4] #alag alag

In [107]:
x

array([[ 2,  3,  4],
       [ 9,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [115]:
x[:,1]=[111,222,333,444] #column change

In [114]:
x

array([[  2, 111,   4],
       [  9, 222,   6],
       [  6, 333,   8],
       [  9, 444,  11]])

In [125]:
x[:2,1:]=[[232,323],[444,555]] #column change

In [124]:
x

array([[  2, 232, 323],
       [  9, 444, 555],
       [  6, 333,   8],
       [  9, 444,  11]])

In [127]:
#insert row
np.append(x,[[0,0,0]],axis=0) # axis 0 because of row if column than 1

array([[  2, 232, 323],
       [  9, 444, 555],
       [  6, 333,   8],
       [  9, 444,  11],
       [  0,   0,   0]])

In [137]:
x=np.append(x,[[0],[0],[0],[0]],axis=1) #add column brackets because of column

In [138]:
x

array([[  2, 232, 323,   0],
       [  9, 444, 555,   0],
       [  6, 333,   8,   0],
       [  9, 444,  11,   0]])

In [142]:
x=np.delete(x,[0,1]) #delete with index

In [143]:
x

array([  9, 444, 555,   0,   6, 333,   8,   0,   9, 444,  11,   0])

In [152]:
np.delete(x,1, axis=0) #whole row

array([  9,   6, 333,   8,   0,   9, 444,  11,   0])

In [154]:
np.delete(y,2,axis=0)

array([[[ 4, 41],
        [ 8, 81],
        [ 7, 71]],

       [[ 3, 31],
        [ 1, 11],
        [ 5, 51]]])

In [155]:
y.size

18

In [156]:
x.size

10

In [161]:
x.reshape(2,5)

array([[  9,   0,   6, 333,   8],
       [  0,   9, 444,  11,   0]])

In [162]:
x.dtype

dtype('int32')

In [167]:
x.astype(float)

array([  9.,   0.,   6., 333.,   8.,   0.,   9., 444.,  11.,   0.])

In [168]:
x.dtype

dtype('int32')

In [172]:
x.astype('int64')

array([  9,   0,   6, 333,   8,   0,   9, 444,  11,   0], dtype=int64)

# nutshell 
## we create arrays
### 1 np.array()
### 2 np.ones()
### 3 np.zeros()
### 4 np.arange()
### 5 np.linspace()
### 6 np.randint()